services:
  - type: web
    name: mwm-podcast-agent
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    healthCheckPath: /healthz
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: CROSSREF_MAILTO
        sync: false
      - key: SEMANTIC_SCHOLAR_API_KEY
        sync: false
      - key: OPENAI_MODEL
        sync: false
      - key: NOTION_TOKEN
        sync: false
      - key: NOTION_DB_ID
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REFRESH_TOKEN
        sync: false
      - key: GOOGLE_DRIVE_PARENT_ID
        sync: false
